### ISSUE TITLE
how to fully uninstall this plugin?

### ISSUE THREAD

**Issue by zilongshanren** [Raimondi/delimitMate#120]
I have uninstalled this plugin, but when I try to input some character like ",',<,(.
then it repeat delimitePlug infinitely.

Really annoying!!!

**Comment by absurd** [comment]
I just encountered the same bug and @madeye is correct, the problem resides in some artifact left behind in the view. Presumably the majority of people afflicted by this bug have

    autocmd BufWinLeave *.* mkview
    autocmd BufWinEnter *.* silent loadview

in their vimrc's.
