### ISSUE TITLE
delimitMate breaks the repeat command

### ISSUE THREAD

**Issue by neitanod** [Raimondi/delimitMate#138]
If in normal mode you type:

    ifunction_name(argument<Esc>

You get:

    function_name(argument)

inserted into the document.  But if you then go down a line and press the "repeat" command (the dot) you just get: 

    argument

inserted into the document.

¿Shouldn't you get everything you typed inserted again?

**Comment by AKurilin** [comment]
Just wanted to express enthusiasm for this being addressed at some point in the future :+1:

**Comment by justinmk** [comment]
There's a patch on vim_dev that allows arrow-key movements on a single line without breaking undo. I'm going to merge into Neovim and be done with it.

**Comment by blueyed** [comment]
@justinmk 
What's the status of this patch? Is it merged into Neovim?
Can you provide a reference otherwise?

**Comment by justinmk** [comment]
@blueyed Here's a reference: https://github.com/neovim/neovim/issues/1025#issuecomment-95357329

The patch is affects only files we have not changed much, so shouldn't be difficult to port.

**Comment by Konfekt** [comment]
How about endorsing the prompt merge of the existent patch into Vim at

https://groups.google.com/forum/m/#!topic/vim_dev/gBumYDSEJoo ?

**Comment by chrisbra** [comment]
As of (7.4.859)[https://github.com/vim/vim/releases/tag/v7.4.849] the fix has been included.

**Comment by Konfekt** [comment]
Thanks! Does the patch need further adjustments in the plugin to make the dot and undo operator work?

**Comment by chrisbra** [comment]
Am 2015-09-02 16:45, schrieb Konfekt:
> Thanks! Does the patch need further adjustments in the plugin to make
> the dot and undo operator work?

Yes. You need to use <C-G>U<cursor> to move without breaking undo/redo.
See the help section in the patch for details.

Best,
Christian

**Comment by DelvarWorld** [comment]
Repeat still does not work with the latest delimitMate. Please re-open this issue.

**Comment by blueyed** [comment]
@DelvarWorld 
Are you using Vim with the required patch?

**Comment by justinmk** [comment]
FYI,  Vim patch 7.4.859 is in Neovim now. https://github.com/neovim/neovim/pull/3306
