### ISSUE TITLE
can't jump when i use S-TAB

### ISSUE THREAD

**Issue by huaihuaiVV** [Raimondi/delimitMate#172]
if i use S-TAB in the following text:

function(abcde|fg);

| is the cursor,  it can't jump out of ( ) pair,
i think should be fix, sometimes i often make some change
of function parameters, so cursor is not beside ")" ,
but should also jump out of ( ) pairs by S-Tab key .

**Comment by qiqiboy** [comment]
> i  <S-Tab>     * pumvisible() ? "\<C-P>" : "\<S-Tab>"
> 	Last set from ~/.vim/bundle/YouCompleteMe/autoload/youcompleteme.vim

<S-Tab> conflict to YouCompleteMe.
