### ISSUE TITLE
Undesired EOL marker

### ISSUE THREAD

**Issue by eloytoro** [Raimondi/delimitMate#195]
The EOL marker option could be so much better if it only added the marker when the delimiters expand with the `delimitMate_expand_cr` option
```javascript
//Undesired behaviour
action
    .next(function() { }); // <- shouldnt apply the marker
    .next(function() {
        /*...*/
    });

// Desired behaviour
action
    .next(function() { })
    .next(function() {
        /*...*/
    });
```

**Comment by eloytoro** [comment]
Thanks for adding this feature.
But it still doesn't work as intended
```javascript
//Undesired behaviour
action
    .next(function() { })
    .next(function() {
        /*...*/
    };) // <- The EOL marker should be inserted after the outer parentheses
```
Also if the EOL marker exists at the end of the line it shouldnt be inserted again.

**Comment by Raimondi** [comment]
Sorry for that, let me know if there is something still missing from this commit.
