### ISSUE TITLE
Matching colon with semi-colon in css files

### ISSUE THREAD

**Issue by wbbutterworth** [Raimondi/delimitMate#208]
This is in my vimrc

au FileType css,less,scss let b:delimitMate_matchpairs="(:),[:],{:},<:>,::;"

There may be a better way to go about this but I want to match : with ; in css files. I'm assuming this doesn't work because of the double colon. Is there a way to escape the first colon?

**Comment by Raimondi** [comment]
Let me know how well it works.
Thanks!

**Comment by wbbutterworth** [comment]
Perfect, my life is that much easier now. Thanks.
