### ISSUE TITLE
Expand CR does not center cursor correctly

### ISSUE THREAD

**Issue by benfranklin79** [Raimondi/delimitMate#217]
My settings are:

```
set backspace=2
let g:delimitMate_expand_cr=2
```

When I have the following:

```
{|}
```

and I hit < CR > I get:

```
{
|}
```

when what I want is:

```
{
|
}
```

**Comment by Raimondi** [comment]
I can't reproduce this.

**Comment by benfranklin79** [comment]
Apologies, this problems seems to have disappeared after messing around enabling/disabling other plugins - yet it's not clear which plugin is the culprit. I will just close this and do further investigation on my own to figure out what was causing it.
