### ISSUE TITLE
quoting a string of text between some delimiter

### ISSUE THREAD

**Issue by fabiosantoscode** [Raimondi/delimitMate#221]
A lot of times I find myself writing this:

> element_by_id(foo)

And wanting to select "foo" with visual mode and then quoting it with single quotes.

Is that possible with delimMate? If not, does it make sense to add it?

Thanks for an awesome plugin!

**Comment by Raimondi** [comment]
The [surround](https://github.com/tpope/vim-surround/) plugin offers this functionality. I don't think it's something delimitMate should do.
