### ISSUE TITLE
<S-BS> doesn't work.

### ISSUE THREAD

**Issue by Raimondi** [Raimondi/delimitMate#23]
This is a conflict with IsForbidden() and insert mode.

**Comment by roachsinai** [comment]
Hi @Raimondi thanks for your plugin, what you posted in the doc told me that <S-BS> may not work in some terminal.

But what you posted sames there is a way to make it by `delimitMate#JumpAny()`,

> NOTE that this will not usually work when using Vim from the
> terminal, see 'delimitMate#JumpAny()' below to see how to fix it.

And after read I did't find how to let it work.

Thanks for any hints!
