### ISSUE TITLE
Ignoring << bit left shift/stream operators in C/C++

### ISSUE THREAD

**Issue by shoban** [Raimondi/delimitMate#230]
When typing out `<<`, delimitMate adds `>>`. In the following example, `|` is the cursor.
```cpp
std::cout << "Hello World"| >>
```
This can often be very annoying. I can only think of two ways of handling this:
1. Use `<S-BS>` to delete the delimiter on the right.
2. Remove `<:>` from `delimitMate_matchpairs`.

Is there a better way of ignoring/handling this?

**Comment by shoban** [comment]
This is not an issue in itself. I don't know where to post this question.

Thanks for an awesome plugin otherwise!

**Comment by Raimondi** [comment]
You can put this in your vimrc:
```viml
au FileType cpp let b:delimitMate_matchpairs = '(:),{:},[:]'
```
That would affect cpp files only. If you want to set a global value for all filetypes, then put this in your vimrc:
```viml
let delimitMate_matchpairs = '(:),{:},[:]'
```

**Comment by shoban** [comment]
Thanks @Raimondi! This is the second method that I described in the issue. It would be great to have a feature where certain patterns (defined by regex?) to be ignored by the plugin.
