### ISSUE TITLE
Is there a way to disable delimitMate for certain characters?

### ISSUE THREAD

**Issue by dorserg** [Raimondi/delimitMate#232]
Is there a way to disable delimitMate functionality for certain characters (but keep it enabled for all the other characters)? E.g. it would make sense to disable autoclosing for "<" in C++ files, as operators << and >> are used quite often.

This can be emulated somewhat by delimitMate_matchpairs (list default matchpairs minus the characters you want to disable delimitMate for), but this feels like a workaround. Something like (non-yet-existent) delimitMate_disabled_matchpairs would be more explicit and convenient.

Or maybe there is an existing option that I've missed that achieves this?

**Comment by Raimondi** [comment]
You can use something like
```viml
au FileType cpp let b:delimitMate_matchpairs = '(:),{:},[:]'
```
that will affect c++ files only.

**Comment by dorserg** [comment]
Ah, yes, this works. I thought `matchpairs` also affects all other characters like single or double quotes, but since that's not the case, specifying `delimitMate_matchpairs = '(:),{:},[:]'` is relatively as easy as (non-existent) `delimitMate_disabled_matchpairs = '<:>'`.
