### ISSUE TITLE
Doesn't work with CJK languages

### ISSUE THREAD

**Issue by IanLewis** [Raimondi/delimitMate#233]
delimitMate interrupts the input of CJK languages making it impossible to do character conversions

**Comment by Raimondi** [comment]
Steps to reproduce it? I don't use any CJK language, so make sure the steps have that in consideration.

**Comment by IanLewis** [comment]
Sorry for not responding to this. All you have to do is type Japanese into the buffer. Typeahead languages (CJK) keep an underlined set of characters that you can convert to other characters later. 
It looks like this: http://futago-life.com/sublime-text3-wiki/_media/img/japanese-input-linux-demo.gif

delimitMate causes you to commit each character as you type making it impossible to do the character conversion later.

You're going to have to install a CJK language input to reproduce.
