### ISSUE TITLE
Issue that only shows up when I open a rust file

### ISSUE THREAD

**Issue by norcalli** [Raimondi/delimitMate#234]
`vim-racer` is installed as well as `rust.vim`. If you open any `*.rs` file then you get the following error 
![image](https://cloud.githubusercontent.com/assets/296363/11859627/7f9195f2-a421-11e5-92ac-dd8412569cd4.png).

**Comment by Raimondi** [comment]
Maybe related to https://github.com/rust-lang/rust.vim/issues/48 ?

**Comment by norcalli** [comment]
It definitely looks like it. Good catch. I suppose I shall try to fix it there or at least ping them on it.
