### ISSUE TITLE
disable auto-completion for '<'

### ISSUE THREAD

**Issue by jabbalaci** [Raimondi/delimitMate#243]
How to disable auto-completion for `<`? If I want to write "less than" (ex. `a < b`), then I don't want the closing pair.

However, when editing HTML for instance, closing `<` is very useful. The ideal solution would be to allow the completion of `<` for certain filetypes.

**Comment by jabbalaci** [comment]
Sorry, it was caused by this line in my .vimrc: `set matchpairs+=<:>`. So it's not delimitMate's fault.

**Comment by anhari** [comment]
For anyone else who stumbles upon this, I tried removing `set matchpairs+=<:>` as well, but that did not work for me.  In my case, I ended up reading `:help 'delimitMate_matchpairs'` and explicitly defined what I wanted to delimitMate to match: `let delimitMate_matchpairs = "(:),[:],{:}"`
