### ISSUE TITLE
vim flooded with "<Plug>delimitMate" when pressing ' or backspace

### ISSUE THREAD

**Issue by mikeyjk** [Raimondi/delimitMate#251]
- [ ] Issue with ' character
- [ ] Issue with backspace key

I am currently experiencing an issue where the document I'm editing is getting repetitively spammed whenever I try and use the apostrophe (') character. I have uninstalled delimitMate via Vundle, yet still seem to be experiencing the issue. Very frustrating.

![dreadful](https://cloud.githubusercontent.com/assets/4499975/20203207/481d1e32-a800-11e6-9d6e-e04764b5cf5f.PNG)

The behaviour is persisting after removing the extension.
The 'fix' I have, is at seemingly arbitrary points in time when the issue manifests, is to run this:

`:mapclear | mapclear <buffer> | mapclear! | mapclear! <buffer>`

Source for the 'fix' (workaround): 

- http://stackoverflow.com/questions/21945038/resetting-all-key-maps-in-vim

I also receive "<Plug>delimitMateBS" when trying to use the backspace key (when the issue occurs). This is slightly less annoying, because my whole buffer doesn't freeze with giant amounts of spam. The backspace key has a 1:1 relationship between being pressed and the strange text being pasted. Whereas, the quote key has a 1:many relationship.

Note: I am using neovim.

Can anyone recommend a more permanent solution to resolve this issue?

**Comment by Raimondi** [comment]
I'm guessing you use sessions or views, that's how the mappings persist. I'm not so sure about why the `'` mapping is broken, maybe another plugin is mapping over it. Use `:help :DelimitMateTest` when you find the issue and paste here the result if you don't see anything suspicious.

**Comment by mikeyjk** [comment]
Thanks Raimondi, I appreciate the response.
I do use some session/view handling, but I'm not really integrating it into my day properly.
I'll try disabling that and seeing how I go.
If I find anything useful re; this I'll paste it here.
Cheers!

**Comment by mikeyjk** [comment]
Closing, haven't seen this happen in quite some time since moving to a docker dev env.

**Comment by EdmundsEcho** [comment]
For those googling: I bumped into this bug recently (May 2019).  I'm working on resetting my session files now.

**Comment by rexagod** [comment]
I'm getting this as well. Also, this is not a `nvim` bug AFAIK since I got this on Vim 8.1. I've tried removing the view files but that doesn't seem to work. Any ideas on how to fix this?

**Comment by Raimondi** [comment]
Post the output of `:DelimitMateTest`

**Comment by dzackgarza** [comment]
I can confirm that this can still happen. It seems to be tied to *specific* files, not just file types: it occurred on an old file I had any time I pressed `'`, but did not happen on a new empty buffer, a new file with the same extension, or a new file with all of the old file's contents pasted in (which was how I got around the issue this time).
