### ISSUE TITLE
Remapping Shift-Tab

### ISSUE THREAD

**Issue by DevinBayly** [Raimondi/delimitMate#252]
Hi there,

I'd really like to make <C-a> do what shift-tab is setup to do by default, but the information in the documentation hasn't helped me make this happen. What should I do to make this possible?

Thanks for helping me out!

**Comment by Raimondi** [comment]
Something like this:

    imap Foo <Plug>delimitMateS-Tab

mentioned in `:help delimitMateMappings`

**Comment by caneta** [comment]
So if I would like to substitute `<S-Tab>` with `<C-J><C-J>`, I'm suppose to write:
```imap <C-J><C-J> <Plug>delimitMateS-Tab```?
I've tried, but it does not work...

**Comment by caneta** [comment]
My fault: I had a conflict with another plugin: `imap <C-L> <Plug>delimitMateS-Tab` did the trick. Sorry about that.
