### ISSUE TITLE
Problem with defining buffer-local matchpairs for $ or `

### ISSUE THREAD

**Issue by lgalke** [Raimondi/delimitMate#254]
Once again I wanted to give insert mode (automagic) bracket completion a try (coming from plain surround's <c-s>). But I immediately ran into the following issue.

Minimal Example:
```autocmd FileType pandoc,tex let b:delimitMate_matchpairs = "$:$"```

yields 
```delimitMate: invalid pairs: $:$```

Is there a problem with the '$' character (I also tried backticks and escaping the $ sign, but it did not help either).

I hope I used the syntax for b:delimitMate_matchpairs correctly..?

**Comment by Raimondi** [comment]
The matchpairs setting is for pairs that have an open char different from the closing char. You need to use `:help 'delimitMate_quotes'` to get what you describe.
