### ISSUE TITLE
Jump with Ctrl+g g will jump over bracket when brackets are in quotes

### ISSUE THREAD

**Issue by shibumi** [Raimondi/delimitMate#257]
Hello,
Thats how you can reproduce this issue:
1. first open a new sh file..
vim $RANDOM.sh

2. Type a double quote " (your cursor is |)
"|"

3. Type a bracket { 
"{|}"

4. Type something like foobar:

"{foobar|}"

5. Now press Ctrl+g g for jumping out of the brackets:

"{foobar}"|

And thats the problem.. you will jump out of the brackets AND the double quotes.. is there a way to only jump out of the brackets and then jumping again if I want to be out of the double quotes?

**Comment by Raimondi** [comment]
Shift-Tab should jump one delimiter, if you can map that to something else then see `:help delimitMateMappings`.

**Comment by shibumi** [comment]
Thanks! I didn't know Shift+Tab. Thanks a lot thats much better than the other shortcut.
