### ISSUE TITLE
Error when opening files with ctrlp.vim

### ISSUE THREAD

**Issue by michaelmior** [Raimondi/delimitMate#261]
I receive the error below when opening a Rust file with ctrlp.vim. Not sure exactly where the issue is (possibly not with delimitMate) but if you have any suggestions, that would be greatly appreciated. Note that this error doesn't occur with all file types and also not when opening files using other methods.

```
Error detected while processing function delimitMate#Get[1]..<SNR>61_get:
line    7:
E716: Key not present in Dictionary: 3.excluded_regions
E15: Invalid expression: s:options.3.excluded_regions
```

**Comment by Raimondi** [comment]
It looks similar to https://github.com/rust-lang/rust.vim/issues/48.

**Comment by michaelmior** [comment]
@Raimondi Thanks for the pointer! It looks like I was using an outdated rust.vim. Upgrading fixed the issue for me!
