### ISSUE TITLE
exclude character from delimiters

### ISSUE THREAD

**Issue by Rafaelsalass** [Raimondi/delimitMate#264]
When writing html files and using the plugin matchit witch close the html tag
I get this ```<h1></h1>>``` when trying to type a html tag with a closing pair,
I want to remove ```<``` from the list of delimiters so this won't happen.

**Comment by Raimondi** [comment]
See `:help 'delimitMate_matchpairs'`

**Comment by Rafaelsalass** [comment]
OMG thank you.
