### ISSUE TITLE
关于缩进的自定义

### ISSUE THREAD

**Issue by BearJean** [Raimondi/delimitMate#274]
想请教，delimitMate大括号不自动换行能不能设置啊
```
比如{}在花括号内回车，格式自动变成
{
cursor
}
光标在cursor位置
```
我想让它输入{时候变成{cursor}的样子，等按下Enter再变成
{
cursor
},因为有时候用大括号初始化多维数组时候总是要一点一点删掉好麻烦。
该怎么设置，谢谢啦~

**Comment by voldikss** [comment]
emmm感觉你好像没说清楚
>比如{}在花括号内回车，格式自动变成
{
cursor
}
光标在cursor位置

所以说在 `{|}` 这种状态下不按回车就不会自动扩展，这不是正常表现吗？
