### ISSUE TITLE
[Feature Request] More matchpairs support

### ISSUE THREAD

**Issue by voldikss** [Raimondi/delimitMate#282]
It seems that this plugin wasn't maintained anymore... 

But I still look forward to the support of the following pairs:
```
{% %}
<!-- -->
/* */
.etc
```
P.S. I've tested that those pairs wasn't support by delimitMate by setting `delimitMate_matchpairs`(and it gave me a lot of errors like `matchpairs must be different from each other...`)

**Comment by Raimondi** [comment]
Matching pairs are limited to single characters, you can not use delimitMate with those examples.

**Comment by voldikss** [comment]
Thanks for your quick response.

Would this feature be supported in the future? I noticed that this was supported in [auto-pairs](https://github.com/jiangmiao/auto-pairs), but it has some other bugs...

So I feel it will be awesome if you include that feature in delimiteMate:relaxed:
