### ISSUE TITLE
Startup errors on 8.2.1300

### ISSUE THREAD

**Issue by williamtstanley** [Raimondi/delimitMate#287]
````
Error detected while processing /Users/XXX/.vim/plugged/delimitmate/plugin/delimitMate.vim[398]..function <SNR>47_setup[30]..<SNR>47_init[3]..<SNR>47_option_init[11]..<SNR>47_set[1]..delimitMate#Set[1]..<SNR>48_set:
line   14:
E716: Key not present in Dictionary: autoclose = a:value
E488: Trailing characters: = a:value
E716: Key not present in Dictionary: matchpairs = a:value
E488: Trailing characters: = a:value
Error detected while processing /Users/XXX/.vim/plugged/delimitmate/plugin/delimitMate.vim[398]..function <SNR>47_setup[30]..<SNR>47_init[6]..<SNR>47_get[1]..delimitMate#Get[1]..<SNR>48_get:
line    7:
E716: Key not present in Dictionary: matchpairs
E15: Invalid expression: s:options.1.matchpairs
Error detected while processing /Users/XXX/.vim/plugged/delimitmate/plugin/delimitMate.vim[398]..function <SNR>47_setup[30]..<SNR>47_init[6]..<SNR>47_option_init[11]..<SNR>47_set[1]..delimitMate#Set[1]..<SNR>48_set:
line   14:
E716: Key not present in Dictionary: matchpairs_list = a:value
E488: Trailing characters: = a:value
Error detected while processing /Users/XXX/.vim/plugged/delimitmate/plugin/delimitMate.vim[398]..function <SNR>47_setup[30]..<SNR>47_init[7]..<SNR>47_get[1]..delimitMate#Get[1]..<SNR>48_get:
line    7:
E716: Key not present in Dictionary: matchpairs_list
E15: Invalid expression: s:options.1.matchpairs_list
Error detected while processing /Users/XXX/.vim/plugged/delimitmate/plugin/delimitMate.vim[398]..function <SNR>47_setup[30]..<SNR>47_init:
line    8:
E896: Argument of filter() must be a List, Dictionary or Blob
delimitMate: each member of a pair in delimitMate_matchpairs must be different from each other.
line   11:
E896: Argument of map() must be a List, Dictionary or Blob
E714: List required
delimitMate: invalid pairs: 0
````
-------

I just upgraded git with `brew install git` and began getting this error. The install updated a number of libs but I don't _think_ it affected my vim install

**Comment by amit1952** [comment]
Having the same problem on Linux Mint 20 after system updated Vim. After the error messages, Vim does start up, and run but without delimitmate functionality.. Tried updating the plugin but the problem remains.
Interestingly, I am also running Neovim with basically the same setup, and, other than delimitmate not functioning, there are no errors..

**Comment by Raimondi** [comment]
Do you guys use sessions ? I just upgraded vim to 8.2.1307 and no errors here.

**Comment by amit1952** [comment]
I don't.

**Comment by yggie** [comment]
I had a similar issue, looks like I was on the old plugin (presumably abandoned):
```
Plugin 'Raimondi/delimitMate'
```

Changing it to:
```
Plugin 'raimondi/delimitmate'
```
fixed the issue

**Comment by yggie** [comment]
having the same issue on macOS 10.14.6, I use `tmux` but use the vanilla `vim` installation

**Comment by brunoadacosta** [comment]
having the same issue on macOS 10.15.6 vim build VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 27 2020 01:26:07)
macOS version

**Comment by larrybotha** [comment]
Confirmed with tmux, too.

macOs 10.14.6
vim 8.2.1300
tmux 3.1b

**Comment by kirchik-martynov** [comment]
same with tmux and without tmux

macOS 10.15.5
vim 8.2.1300

**Comment by Raimondi** [comment]
Could any of you get a minimal setup that reproduces the problem and share it? I need to see the issue in order to fix it.

`cd` into delimitMate's repo and run `vim -N -i NONE -u basic_vimrc`, then modify basic_vimrc until you reproduce the problem and share it here.

**Comment by Elidrake** [comment]
A temporary fix; I downgraded my version of Vim by reverting the Brew formula.

`brew edit vim`

Paste in the old version [here](https://raw.githubusercontent.com/Homebrew/homebrew-core/6a8f5692ae05d70f347ce194d9cd892370712239/Formula/vim.rb).

`brew reinstall vim`

And I was back to normal.

It does appear to specifically be Mac OS Catalina vim 8.2.1300; somewhere between there and 8.2.1307 may have had a fix.  Brew specifically only updates the Vim releases "every 50 releases on multiples of 50".

**Comment by davidjb** [comment]
@Raimondi The problem happens with this minimal basic_vimrc:

```vimrc
so ./test/_setup.vim
```

which can be further simplified down to the first line of `_setup.vim` at https://github.com/Raimondi/delimitMate/blob/master/test/_setup.vim#L1.

I'm using the same Vim version as above on Mac, as installed by Homebrew.

**Comment by bfontaine** [comment]
@Elidrake This is not specific to Mac; I have the same issue with Linuxbrew on Ubuntu.

**Comment by Raimondi** [comment]
The issue started with 8.2.1274 and it's gone with 8.2.1306. As @davidjb pointed out, you just need to have delimitMate installed to get the errors. I can reproduce it by compiling vim from source.

**Comment by Raimondi** [comment]
It seems to work here, let me know how it goes on your end.

**Comment by williamtstanley** [comment]
Works perfectly! Thanks for the quick response I appreciate it.

**Comment by andys8** [comment]
I ran into this issue on Ubuntun/Mint. Newest version in [this PPA](https://launchpad.net/~jonathonf/+archive/ubuntu/vim) is currently 8.2.1303. Rolling back to 8.1.2269 for now.

**Comment by Raimondi** [comment]
@An

**Comment by Raimondi** [comment]
> I ran into this issue on Ubuntun/Mint. Newest version in [this PPA](https://launchpad.net/~jonathonf/+archive/ubuntu/vim) is currently 8.2.1303. Rolling back to 8.1.2269 for now. 

@andys8: Did you update delimitMate?

**Comment by andys8** [comment]
I think so. I used `PlugUpdate`. Not sure if the update actually worked, because of the error. I found this thread and expected it not to work because of the version. Didn't look further into it after that.

**Comment by amadeus** [comment]
The issue should be fixed according to this thread. It might be worth putting a bit more effort into making sure you are all up to date 😀

**Comment by andys8** [comment]
I can confirm delimitmate 16687aec24d803bc76cae2d7bfe2b73b1cdda4ef and Vim 8.2 1303 are in fact working. I guess my mistake was to first update Vim and then not being able to update delimitmate with vim-plug's `:PlugUpdate`. Not sure though.
