### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by elig0n** [Raimondi/delimitMate#289]
installed via vim-plugged
the plugin seems to get loaded with no special errors whatsoever
so I tried typing in an empty buffer characters like [,(,'," but no closing match was added. 
Am I missing something?

:DelimitMateTest returns:

    delimitMate Report
    ==================
    
    * Options: ( ) default, (g) global, (b) buffer
    
    ( ) delimitMate_apostrophes = ''
    ( ) delimitMate_apostrophes_list = []
    ( ) delimitMate_autoclose = 1
    ( ) delimitMate_balance_matchpairs = 0
    ( ) delimitMate_eol_marker = ''
    ( ) delimitMate_excluded_regions = 'Comment'
    ( ) delimitMate_excluded_regions_enabled = 1
    ( ) delimitMate_excluded_regions_list = ['Comment']
    ( ) delimitMate_expand_cr = 0
    ( ) delimitMate_expand_inside_quotes = 0
    ( ) delimitMate_expand_space = 0
    ( ) delimitMate_insert_eol_marker = 1
    ( ) delimitMate_jump_expansion = 0
    ( ) delimitMate_left_delims = ['(', '{', '[']
    ( ) delimitMate_matchpairs = '(:),{:},[:]'
    ( ) delimitMate_matchpairs_list = [['(', ')'], ['{', '}'], ['[', ']']]
    ( ) delimitMate_nesting_quotes = []
    ( ) delimitMate_quotes = '" '' `'
    ( ) delimitMate_quotes_list = ['"', '''', '`']
    ( ) delimitMate_right_delims = [')', '}', ']']
    ( ) delimitMate_smart_matchpairs = '^\%(\w\|\!\|[£$]\|[^[:punct:][:space:]]\)'
    ( ) delimitMate_smart_quotes = '\%(\w\|[^[:punct:][:space:]"''`]\|\%(\\\\\)*\\\)\%#\|\%#\%(\w\|[^[:space:][:punct:]"''`]\)'
    ( ) delimitMate_tab2exit = 1
    
    ( ) g:delimitMate_excluded_ft = ''
    --------------------
    
    * Mappings:
    
    i  )            @<Plug>delimitMate)
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 301
    i  }            @<Plug>delimitMate}
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 301
    i  ]            @<Plug>delimitMate]
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 301
    i  (            @<Plug>delimitMate(
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 291
    i  {            @<Plug>delimitMate{
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 291
    i  [            @<Plug>delimitMate[
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 291
    i  "            @<Plug>delimitMate"
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 313
    i  '            @<Plug>delimitMate'
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 313
    i  `            @<Plug>delimitMate`
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 313
    i  <BS>        * <C-G>u<C-H>
    	Last set from ~/.vim/vimrc.mappings line 218
    i  <S-BS>       @<Plug>delimitMateS-BS
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 339
    i  <S-Tab>       <Plug>(MUcompleteBwd)
    	Last set from ~/.vim/plugged/vim-mucomplete/plugin/mucomplete.vim line 29
    i  <C-G>g       @<Plug>delimitMateJumpMany
    	Last set from ~/.vim/plugged/delimitMate/plugin/delimitMate.vim line 359
    --------------------
    
    * Showcase:
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    [... configuration ... ]

    VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 22 2020 19:53:01)
    Included patches: 1-1272
    Compiled by Arch Linux
    Huge version with GTK3 GUI.  Features included (+) or not (-):
    +acl               +cmdline_hist      +ex_extra          +jumplist          +mouse_dec         +perl/dyn          +sound             +textprop          +writebackup
    +arabic            +cmdline_info      +extra_search      +keymap            +mouse_gpm         +persistent_undo   +spell             +timers            +X11
    +autocmd           +comments          -farsi             +lambda            -mouse_jsbterm     +popupwin          +startuptime       +title             -xfontset
    +autochdir         +conceal           +file_in_path      +langmap           +mouse_netterm     +postscript        +statusline        +toolbar           +xim
    -autoservername    +cryptv            +find_in_path      +libcall           +mouse_sgr         +printer           -sun_workshop      +user_commands     -xpm
    +balloon_eval      +cscope            +float             +linebreak         -mouse_sysmouse    +profile           +syntax            +vartabs           +xsmp_interact
    +balloon_eval_term +cursorbind        +folding           +lispindent        +mouse_urxvt       +python/dyn        +tag_binary        +vertsplit         +xterm_clipboard
    +browse            +cursorshape       -footer            +listcmds          +mouse_xterm       +python3/dyn       -tag_old_static    +virtualedit       -xterm_save
    ++builtin_terms    +dialog_con_gui    +fork()            +localmap          +multi_byte        +quickfix          -tag_any_white     +visual            
    +byte_offset       +diff              +gettext           +lua/dyn           +multi_lang        +reltime           +tcl/dyn           +visualextra       
    +channel           +digraphs          -hangul_input      +menu              -mzscheme          +rightleft         +termguicolors     +viminfo           
    +cindent           +dnd               +iconv             +mksession         +netbeans_intg     +ruby/dyn          +terminal          +vreplace          
    +clientserver      -ebcdic            +insert_expand     +modify_fname      +num64             +scrollbind        +terminfo          +wildignore        
    +clipboard         +emacs_tags        +ipv6              +mouse             +packages          +signs             +termresponse      +wildmenu          
    +cmdline_compl     +eval              +job               +mouseshape        +path_extra        +smartindent       +textobjects       +windows           
       system vimrc file: "/etc/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
      system gvimrc file: "/etc/gvimrc"
        user gvimrc file: "$HOME/.gvimrc"
    2nd user gvimrc file: "~/.vim/gvimrc"
           defaults file: "$VIMRUNTIME/defaults.vim"
        system menu file: "$VIMRUNTIME/menu.vim"
      fall-back for $VIM: "/usr/share/vim"
    Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
    Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
    --------------------

**Comment by Raimondi** [comment]
Is the "Showcase" section empty in the test result? I'm not sure what's going on, the mappings are set.
