### ISSUE TITLE
delimitMate not working with terryma/vim-multiple-cursors

### ISSUE THREAD

**Issue by pengux** [Raimondi/delimitMate#290]
When using multiple cursors, typing `"` results in the string `<Plug>delimitMate` instead.

**Comment by Raimondi** [comment]
Vim doesn't have a multiple cursor feature, I think the problem is in the plugin that provides that feature.

**Comment by pengux** [comment]
Of course, the plugin is terryma/vim-multiple-cursors as mentioned. If compatibility with that plugin is something delimitMate may never have, then for anyone who finds this issue, you can toggle `DelimitMateOff` and `DelimitMateOn` when using multiple cursors.

**Comment by Raimondi** [comment]
That plugin is deprecated, I'd try with the suggested alternative https://github.com/mg979/vim-visual-multi
