### ISSUE TITLE
Backspace key removes extra space

### ISSUE THREAD

**Issue by tetomi** [Raimondi/delimitMate#297]
I initially asked this [here](https://vi.stackexchange.com/questions/34734/backspace-removes-extra-space-after-installing-delimitmate) on Vi and Vim Stack Exchange, so please take a look at that for details.

**Expected behavior**
When you press a backspace key, it should remove only one space.

**What happens now**
When you press a backspace key, it removes extra space.

**Environment**
NVIM v0.5.1

That being said, it's absolutely fine to remove extra space when you are inside a matching pair, and  remove both leading and trailing space at the same time when you press a backspace key.

**Comment by tetomi** [comment]
I'm a Rust programmer so hope it's okay to demonstrate this behavior in Rust file.

**Steps to reproduce**

1. Install Rust
2. Create a directory and a main file(main.rs) with one command `cargo new hello`. The main.rs file is created inside src directory that is also created with the command.
3. Go to the hello directory and execute the following command `vim src/main.rs`. (I mapped the `vim` command to neovim, so here it is actually executing neovim.)
4. Inside main.rs, you see the default code Rust created as follows.

```
fn main() {
    println!("Hello, world!");
}
```

5. Under the line `println!("Hello, world!");`, start typing `let hello  |` <- Here the pipe symbol indicates my cursor and note that there are two spaces between `o` as in `hello` and the cursor.
6. Now the code looks like this.

```
fn main() {
    println!("Hello, world!");
    let hello  |
}
```

7. Now press the backspace key once and see that it removes two spaces instead of one.

Oddly enough, if you stop typing at `let hel` and add two spaces afterwards and press backspace key, it only removes one space, which is a correct behavior.
So, this issue happens depending on where, in a line of code, you press backspace key.
To demonstrate this, see the following.

```
fn main() {
    println!("Hello, world!");
    let hel  |
}
```
When you press the backspace key at this location, you will see that it correctly removes only one space.

delimitMate Report
==================

* Options: ( ) default, (g) global, (b) buffer

( ) delimitMate_apostrophes = ''
( ) delimitMate_apostrophes_list = []
( ) delimitMate_autoclose = 1
( ) delimitMate_balance_matchpairs = 0
( ) delimitMate_eol_marker = ''
( ) delimitMate_excluded_regions = 'Comment'
( ) delimitMate_excluded_regions_enabled = 1
( ) delimitMate_excluded_regions_list = ['Comment']
( ) delimitMate_expand_cr = 0
( ) delimitMate_expand_inside_quotes = 0
( ) delimitMate_expand_space = 0
( ) delimitMate_insert_eol_marker = 1
( ) delimitMate_jump_expansion = 0
( ) delimitMate_left_delims = ['(', '{', '[']
( ) delimitMate_matchpairs = '(:),{:},[:]'
( ) delimitMate_matchpairs_list = [['(', ')'], ['{', '}'], ['[', ']']]
( ) delimitMate_nesting_quotes = []
( ) delimitMate_quotes = '" '' `'
( ) delimitMate_quotes_list = ['"', '''', '`']
( ) delimitMate_right_delims = [')', '}', ']']
( ) delimitMate_smart_matchpairs = '^\%(\w\|\!\|[£$]\|[^[:punct:][:space:]]\)'
( ) delimitMate_smart_quotes = '\%(\w\|[^[:punct:][:space:]"''`]\|\%(\\\\\)*\\\)\%#\|\%#\%(\w\|[
( ) delimitMate_tab2exit = 1

( ) g:delimitMate_excluded_ft = ''
--------------------

* Mappings:

i  )            @<Plug>delimitMate)
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 301
i  }            @<Plug>delimitMate}
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 301
i  ]            @<Plug>delimitMate]
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 301
i  (            @<Plug>delimitMate(
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 291
i  {            @<Plug>delimitMate{
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 291
i  [            @<Plug>delimitMate[
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 291
i  "            @<Plug>delimitMate"
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 313
i  '            @<Plug>delimitMate'
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 313
i  `            @<Plug>delimitMate`
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 313
i  <BS>         @<Plug>delimitMateBS
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 330
i  <S-BS>       @<Plug>delimitMateS-BS
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 339
i  <S-Tab>      @<Plug>delimitMateS-Tab
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 354
i  <C-G>g       @<Plug>delimitMateJumpMany
        Last set from ~/.data/plugged/delimitMate/plugin/delimitMate.vim line 359
--------------------

* Showcase:

Open: (|)
Delete: |
Exit: ()|

Open: {|}
Delete: |
Exit: {}|

Open: [|]
Delete: |
Exit: []|

Open: "|"
Delete: |
Exit: ""|

Open: '|'
Delete: |
Exit: ''|

Open: `|`
Delete: |
Exit: ``|

 * Vim configuration:

filetype detection:ON  plugin:ON  indent:ON

--- Options ---
  columns=96          lines=57            scroll=27
  helplang=en         modified            window=56
  runtimepath=~/.config/nvim,~/.data/plugged/delimitMate,/etc/xdg/nvim,~/.local/share/nvim/site,

NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT
Compiled by runner@fv-az87-829

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
--------------------

**Comment by Raimondi** [comment]
I think it's not related to delimitmate, I removed the mapping and the issue continued, which , along with your comment about the behaviour when the was an extra space, I suspected `:help 'softtabstop'`. So, I did the following:

1. Start neovim with `nvim --clean´.
2. Execute `:set sts=3`.
3. Start typing `123` followed by 3 spaces.
4. Exit insert mode with `Esc`.
5. Press `a` to enter insert mode at the end of the line.
6. Press `Backspace` once.
7. The 3 spaces are deleted together.

You have to exit insert mode after inserting the spaces for backspace to behave that way. You can try changing the value of softtabstop to zero to see the difference.

Is that the behaviour that you were reporting?

**Comment by Raimondi** [comment]
You can set sts in ~/.vim/after/ftplugin/rust.vim to overrule the built-in ftplugin for rust.

The second paragraph in `:help ins-softabstop` describes the behaviour at hand. Not sure what else could I try to fix it in delimitMate itself.
