### ISSUE TITLE
add support for python f-strings

### ISSUE THREAD

**Issue by gmnr** [Raimondi/delimitMate#300]
I am failing at configuring delimitMate to work with f-strings in python.

The desired behavior is that, in python, prepending f to the pair of single (') or double (") quotes still triggers the autocompletion, without repeating the f.

Thank you in advance for your help!

**Comment by BTrey** [comment]
+1 for this. Came here looking for a solution to exactly this problem.

**Comment by 0xKira** [comment]
I also encountered this problem and finally solved it.

Add this line to your vimrc.
```vim
au FileType python let b:delimitMate_smart_quotes = '\%(_\|[^[:punct:][:space:]bfu]\|\%(\\\\\)*\\\)\%#\|\%#\%(\w\|[^[:space:][:punct:]]\)'
```
This acts like the default behavior except you type a quote after b/f/u(possible python string prefixes)
