### ISSUE TITLE
<CR> curly-brace expansion results in incorrect indention

### ISSUE THREAD

**Issue by lynndylanhurley** [Raimondi/delimitMate#53]
this is what I get when I run DelimitMateTest:

```
Open: {|}
Delete: |
Exit: {}|
Space: { | }
Delete space: {|}
Car return: {
    |
    }
    Delete car return: {
    |
        }
```

**Comment by cmcginty** [comment]
@lynndylanhurley  yes, i was going to say the same thing! This needs to be on the front page. I would also add the following options as defaults:

    let g:delimitMate_jump_expansion = 1
    let g:delimitMate_balance_matchpairs = 1
